name: 'purge-jsdelivr-for-directory'
description:
  'Refresh the cache of jsdelivr for a folder in the current repository'
author: 'bling-yshs'
branding:
  icon: activity
  color: orange
inputs:
  token:
    description: 'Repo token'
    required: false
    default: ${{ github.token }}
  path:
    description: 'Some directories in the current repository'
    required: false
    default: ''
  retry:
    description: 'retry times for each file'
    required: false
    default: '10'
  branchName:
    description:
      'repo branch name, if left blank, it means is default branch of the
      repository'
    required: false
    default: ''

runs:
  using: node20
  main: dist/index.js
