name: test action
run-name: test action
on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: Hello world action step
        id: hello
        uses: bling-yshs/purge-jsdelivr-for-directory@v1
        with:
          path: |
            dist
            src
